# A generic, single database configuration for Alembic migrations.

[alembic]
# path to migration script directory
script_location = alembic

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = .

# template used to generate migration file names
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
timezone = UTC

# max length of characters in slug
max_slug_length = 40

# set to 'true' to run the environment during the 'revision' command
revision_environment = false

# set to 'true' to allow .pyc and .pyo files without a corresponding .py file
sourceless = false

# version location specification
version_locations = %(here)s/alembic/versions

# set to 'true' to search version_locations recursively
version_path_separator = os

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
